### ISSUE TITLE
Host site for tutorial suspended

### ISSUE THREAD

**Issue by OptogeneticsandNeuralEngineeringCore** [danarteaga/Raspberry-Pi-Home-Security-System#1]
All links on the tutorial are broken. Consider pdf or hosting directly through GitHub Pages (their themes are easy to implement) or overlay a sweet highly customization-able theme (I recommend HydeJack). Let me know if I can help, I was just about to implement/improve/3D design parts for 3D printing.

**Comment by danarteaga** [comment]
Thanks for letting me know! I will try to fix in the next day or too.

**Comment by danarteaga** [comment]
Fixed, moved all website files to github directly at https://danarteaga.github.io/. Thanks again. Also, will add a few needed updates to this project tomorrow - need to perform system updates on my pi as some packages have changed since I made this last year causing some issues. Look for new commits soon.
